version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: parserdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  postgres:
    driver: bridge
volumes:
  postgres-data: